//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoMoney.Models.Models
{
    using System;
    using System.Collections.Generic;
    
    public class DemoMoneyTable
    {
        public int ID { get; set; }
        public System.DateTime date { get; set; }
        public string category { get; set; }
        public int money { get; set; }
        public string remark { get; set; }
        public string InAndOut { get; set; }
        public string DeleteOrNot { get; set; }
    }

    public class LietDemoMoneyTable : DemoMoneyTable
    {
        public List<DemoMoneyTable> listdemoMoneyTables { get; set; }
    }
}
